package com.hospital.dto;

import com.hospital.model.ConsultationPayment;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import lombok.Data;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;

public class ConsultationPaymentDtos {


    @Data
    public static class ReceiptLineItemDto {
        private String particulars;
        private BigDecimal amount;
    }

    @Data
    public static class CreateConsultationPaymentRequest {
        @NotNull
        private UUID appointmentId;

        @NotNull
        @Positive
        private BigDecimal amountPaid;

        @NotNull
        private ConsultationPayment.PaymentMode paymentMode;

        // Nullable for CASH/UPI etc.
        private String paymentReference;

        // Optional override; recommended to use authenticated user.
        private String receivedByName;

        @NotNull
        @Positive
        private BigDecimal consultationFee;

        // Staff-entered Sr. No / Particulars / Amount snapshot.
        // Sr. No is generated by frontend (1..n), but backend will persist only what you send.
        @NotNull
        private List<ReceiptLineItemDto> lineItems;
    }


    @Data
    public static class CreateConsultationPaymentResponse {
        private UUID consultationPaymentId;
    }
}

