import React, { useState, useEffect, useCallback } from 'react';
import api from '../services/api';
import { LoadingSpinner, Badge, EmptyState, Tabs } from '../components/Common';
import { ActionMenu, ConfirmDialog, Dialog, FilterBar, FormField, PageHeader, Pagination } from '../components/SharedUI';
import { useToast } from '../context/ToastContext';
import { consultationPaymentApi } from '../services/consultationPaymentApi';
import { consultationReceiptApi, printBlob, saveBlob } from '../services/receiptApi';



const Appointments = () => {
  const { showToast } = useToast();
  const [appointments, setAppointments] = useState([]);
  const [loading, setLoading] = useState(true);
  
  // Filters state
  const [statusFilter, setStatusFilter] = useState('all');
  const [dateFilter, setDateFilter] = useState('');
  
  // Pagination state
  const [page, setPage] = useState(0);
  const [size, setSize] = useState(10);
  const [totalPages, setTotalPages] = useState(0);
  const [totalElements, setTotalElements] = useState(0);
  
  // Sorting state
  const [sortBy, setSortBy] = useState('createdAt');
  const [sortDirection, setSortDirection] = useState('DESC');
  
  const [updating, setUpdating] = useState(null);
  const [cancelTarget, setCancelTarget] = useState(null);
  const showLegacyPagination = false;

  const fetchAppointments = useCallback(async () => {
    setLoading(true);
    try {
      const params = { page, size, sortBy, sortDirection, date: dateFilter, status: statusFilter };
      const response = await api.get('/appointments/hospital/paged', { params });
      const pagedData = response;
      if (pagedData) {
        setAppointments(pagedData.content || []);
        setTotalPages(pagedData.totalPages || 0);
        setTotalElements(pagedData.totalElements || 0);
      } else {
        setAppointments([]);
      }
    } catch (error) {
      console.error('Error fetching appointments:', error);
      setAppointments([]);
    } finally {
      setLoading(false);
    }
  }, [page, size, sortBy, sortDirection, dateFilter, statusFilter]);

  useEffect(() => {
    fetchAppointments();
  }, [fetchAppointments]);

  const updateStatus = async (id, status) => {
    setUpdating(id);
    try {
      await api.patch(`/appointments/hospital/${id}/status`, { status });
      await fetchAppointments();
      showToast(`Appointment marked as ${status}.`, { type: 'success' });
    } catch (error) {
      showToast(error.message || 'Could not update the appointment.', { type: 'error', title: 'Update failed' });
    } finally {
      setUpdating(null);
    }
  };

  const [paymentModal, setPaymentModal] = useState({
    open: false,
    appointment: null,
  });
  const [existingAppointmentReceipt, setExistingAppointmentReceipt] = useState(null);
  const [checkingAppointmentReceipt, setCheckingAppointmentReceipt] = useState(false);

  const [paymentForm, setPaymentForm] = useState({
    paymentMode: 'CASH',
    amountPaid: '',
    paymentReference: '',
    // Line items entered by receptionist (Sr. No is auto-generated by backend)
    lineItems: [
      {
        particulars: 'Consultation Fee',
        amount: ''
      }
    ],
  });

  const openPaymentModal = async (appt) => {
    const consultationFee = appt?.doctor?.consultationFee;
    setPaymentModal({ open: true, appointment: appt });
    setExistingAppointmentReceipt(null);
    setCheckingAppointmentReceipt(true);

    const fee = consultationFee != null ? Number(consultationFee) : 0;
    setPaymentForm({
      paymentMode: 'CASH',
      amountPaid: fee ? String(fee) : '',
      paymentReference: '',
      lineItems: [
        {
          particulars: 'Consultation Fee',
          amount: fee ? String(fee) : '',
        },
      ],
    });

    try {
      const receipt = appt?.id ? await consultationReceiptApi.activeByAppointment(appt.id) : null;
      setExistingAppointmentReceipt(receipt || null);
    } catch {
      setExistingAppointmentReceipt(null);
    } finally {
      setCheckingAppointmentReceipt(false);
    }
  };

  const closePaymentModal = () => {
    setPaymentModal({ open: false, appointment: null });
    setExistingAppointmentReceipt(null);
    setCheckingAppointmentReceipt(false);
  };

  const submitPaymentAndPrintPdf = async (opts) => {
    const appt = paymentModal.appointment;

    if (!appt?.id) throw new Error('Missing appointment id');
    if (existingAppointmentReceipt) {
      throw new Error(`Receipt ${existingAppointmentReceipt.receiptNumber} already exists for this appointment.`);
    }

    const consultationFee = appt?.doctor?.consultationFee;
    if (!consultationFee || Number(consultationFee) <= 0) {
      throw new Error('Consultation fee not available');
    }

    const amountPaid = Number(paymentForm.amountPaid);
    if (Number.isNaN(amountPaid) || amountPaid <= 0) {
      throw new Error('Invalid amount paid');
    }

    const lineItems = (paymentForm.lineItems || []).map((li) => ({
      particulars: li.particulars?.trim(),
      amount: li.amount === '' || li.amount == null ? null : Number(li.amount),
    }));

    const payload = {
      appointmentId: appt.id,
      consultationFee: Number(consultationFee),
      amountPaid,
      paymentMode: String(paymentForm.paymentMode).toUpperCase(),
      paymentReference: paymentForm.paymentReference?.trim() ? paymentForm.paymentReference.trim() : null,
      receivedByName: null,
      lineItems,
    };

    const resp = await consultationPaymentApi.createPayment(payload);
    const consultationPaymentId = resp?.consultationPaymentId;
    if (!consultationPaymentId) throw new Error('No consultationPaymentId returned');

    // Always “Save & Print” = download receipt immediately (for now, to avoid changing backend snapshot behavior)
    const blob = await consultationReceiptApi.saveAndPrintByPaymentId(consultationPaymentId);
    saveBlob(blob, 'consultation-receipt.pdf');

    if (opts?.markCompleted) {
      await api.patch(`/appointments/hospital/${appt.id}/status`, { status: 'completed' });
      fetchAppointments();
    }
  };

  const printExistingReceipt = async () => {
    if (!existingAppointmentReceipt?.id) return;
    const blob = await consultationReceiptApi.downloadById(existingAppointmentReceipt.id);
    printBlob(blob);
  };

  const downloadExistingReceipt = async () => {
    if (!existingAppointmentReceipt?.id) return;
    const blob = await consultationReceiptApi.downloadById(existingAppointmentReceipt.id);
    saveBlob(blob, `${existingAppointmentReceipt.receiptNumber}.pdf`);
  };




  const handlePageChange = (newPage) => {
    if (newPage >= 0 && newPage < totalPages) {
      setPage(newPage);
    }
  };

  const handleSizeChange = (newSize) => {
    setSize(newSize);
    setPage(0); // Reset to first page
  };

  const handleSort = (field) => {
    if (sortBy === field) {
      setSortDirection(sortDirection === 'ASC' ? 'DESC' : 'ASC');
    } else {
      setSortBy(field);
      setSortDirection('DESC');
    }
    setPage(0); // Reset to first page
  };

  const getSortIcon = (field) => {
    if (sortBy !== field) return '⇅';
    return sortDirection === 'ASC' ? '↑' : '↓';
  };

  const countByStatus = (s) => {
    // Note: In a real implementation, we'd get counts from the backend
    // For now, we'll show the current page filtered count
    return appointments.filter(a => a.status === s).length;
  };

  const tabs = [
    { value: 'all', label: 'All', count: totalElements },
    { value: 'pending', label: 'Pending', count: countByStatus('pending') },
    { value: 'confirmed', label: 'Confirmed', count: countByStatus('confirmed') },
    { value: 'completed', label: 'Completed', count: countByStatus('completed') },
    { value: 'cancelled', label: 'Cancelled', count: countByStatus('cancelled') },
  ];

  return (
    <div>
      <PageHeader title="Appointments" subtitle={`${totalElements} total appointments`} eyebrow="Scheduling" />

      <Tabs tabs={tabs} active={statusFilter} onChange={(val) => { setStatusFilter(val); setPage(0); }} />

      {paymentModal.open && (
        <Dialog
          title="Collect Consultation Payment & Print"
          onClose={closePaymentModal}
          size="lg"
        >
          <div style={{ display: 'grid', gap: 12, minWidth: 320 }}>
            <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>
              Consultation fee: <strong>₹{paymentForm.amountPaid ? paymentForm.amountPaid : (paymentModal.appointment?.doctor?.consultationFee ?? 0)}</strong>
            </div>

            {checkingAppointmentReceipt && (
              <div className="alert alert-info">
                Checking whether this appointment already has a receipt...
              </div>
            )}

            {existingAppointmentReceipt && (
              <div className="alert alert-error">
                Receipt {existingAppointmentReceipt.receiptNumber} already exists for this appointment. New receipt creation is disabled.
                <div style={{ display: 'flex', gap: 8, marginTop: 10, flexWrap: 'wrap' }}>
                  <button type="button" className="btn btn-secondary btn-sm" onClick={printExistingReceipt}>
                    Print Existing
                  </button>
                  <button type="button" className="btn btn-secondary btn-sm" onClick={downloadExistingReceipt}>
                    Download PDF
                  </button>
                </div>
              </div>
            )}

            <div className="form-group">
              <label>Payment Mode</label>
              <select
                value={paymentForm.paymentMode}
                onChange={(e) => setPaymentForm((f) => ({ ...f, paymentMode: e.target.value }))}
                className="form-control"
              >
                <option value="CASH">Cash</option>
                <option value="UPI">UPI</option>
                <option value="CARD">Card</option>
                <option value="NET_BANKING">Net Banking</option>
                <option value="OTHER">Other</option>
              </select>
            </div>

            <div className="form-group">
              <label>Line Items</label>

              <div style={{ display: 'grid', gridTemplateColumns: '60px 1fr 140px', gap: 8, alignItems: 'center' }}>
                <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>Sr</div>
                <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>Particulars</div>
                <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>Amount</div>
              </div>

              <div style={{ display: 'grid', gap: 10, marginTop: 10 }}>
                {paymentForm.lineItems.map((li, idx) => (
                  <div key={idx} style={{ display: 'grid', gridTemplateColumns: '60px 1fr 140px', gap: 8, alignItems: 'center' }}>
                    <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text)' }}>{idx + 1}</div>

                    <input
                      value={li.particulars}
                      onChange={(e) => {
                        const v = e.target.value;
                        setPaymentForm((f) => ({
                          ...f,
                          lineItems: f.lineItems.map((x, i) => i === idx ? { ...x, particulars: v } : x),
                        }));
                      }}
                      className="form-control"
                      placeholder="Particulars"
                    />

                    <input
                      value={li.amount}
                      onChange={(e) => {
                        const v = e.target.value;
                        setPaymentForm((f) => ({
                          ...f,
                          lineItems: f.lineItems.map((x, i) => i === idx ? { ...x, amount: v } : x),
                        }));
                      }}
                      className="form-control"
                      placeholder="0.00"
                      inputMode="decimal"
                    />
                  </div>
                ))}
              </div>

              <div style={{ marginTop: 10, display: 'flex', gap: 10, flexWrap: 'wrap' }}>
                <button
                  className="btn btn-secondary"
                  type="button"
                  onClick={() => {
                    setPaymentForm((f) => ({
                      ...f,
                      lineItems: [...f.lineItems, { particulars: '', amount: '' }],
                    }));
                  }}
                >
                  + Add Line
                </button>

                <button
                  className="btn btn-secondary"
                  type="button"
                  disabled={paymentForm.lineItems.length <= 1}
                  onClick={() => {
                    setPaymentForm((f) => ({
                      ...f,
                      lineItems: f.lineItems.slice(0, Math.max(1, f.lineItems.length - 1)),
                    }));
                  }}
                >
                  Remove Last
                </button>
              </div>
            </div>

            <div className="form-group">
              <label>Amount Paid</label>
              <input
                value={paymentForm.amountPaid}
                onChange={(e) => setPaymentForm((f) => ({ ...f, amountPaid: e.target.value }))}
                className="form-control"
                placeholder="Enter amount"
              />
            </div>


            <div className="form-group">
              <label>Payment Reference (optional)</label>
              <input
                value={paymentForm.paymentReference}
                onChange={(e) => setPaymentForm((f) => ({ ...f, paymentReference: e.target.value }))}
                className="form-control"
                placeholder="UTR / Txn ID / etc."
              />
            </div>

            <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 6, flexWrap: 'wrap' }}>
              <button className="btn btn-secondary" onClick={closePaymentModal}>
                Cancel
              </button>

              <button
                className="btn btn-secondary"
                disabled={checkingAppointmentReceipt || !!existingAppointmentReceipt}
                onClick={async () => {
                  try {
                    await submitPaymentAndPrintPdf({ markCompleted: false });
                    closePaymentModal();
                  } catch (e) {
                    showToast(e.message || String(e), { type: 'error', title: 'Receipt failed' });
                  }
                }}
              >
                Print Receipt (PDF)
              </button>

              <button
                className="btn btn-primary"
                disabled={checkingAppointmentReceipt || !!existingAppointmentReceipt}
                onClick={async () => {
                  try {
                    await submitPaymentAndPrintPdf({ markCompleted: true });
                    closePaymentModal();
                  } catch (e) {
                    showToast(e.message || String(e), { type: 'error', title: 'Payment failed' });
                  }
                }}
              >
                Save & Print Receipt (PDF)
              </button>
            </div>
          </div>
        </Dialog>
      )}

      {/* Table Controls */}

      <FilterBar>
        <FormField label="Appointment date">
          <input
            type="date"
            value={dateFilter}
            onChange={e => {
              setDateFilter(e.target.value);
              setPage(0);
            }}
          />
        </FormField>
        <FormField label="Records per page">
          <select
            value={size} 
            onChange={e => handleSizeChange(Number(e.target.value))}
          >
            <option value={5}>5</option>
            <option value={10}>10</option>
            <option value={15}>15</option>
            <option value={100}>100</option>
          </select>
        </FormField>
        {dateFilter && <button className="btn btn-secondary" onClick={() => setDateFilter('')}>Clear date</button>}
      </FilterBar>

      <div className="table-wrap appointments-table-wrap">
        {loading ? <LoadingSpinner /> : appointments.length === 0 ? (
          <EmptyState icon="📅" title="No appointments found" />
        ) : (
          <>
            {/* Desktop Table */}
            <table className="appointments-table-desktop">

              <thead>
                <tr>
                  <th onClick={() => handleSort('tokenNumber')} style={{ cursor: 'pointer' }}>
                    Token {getSortIcon('tokenNumber')}
                  </th>
                  <th onClick={() => handleSort('patient')} style={{ cursor: 'pointer' }}>
                    Patient {getSortIcon('patient')}
                  </th>
                  <th onClick={() => handleSort('doctor')} style={{ cursor: 'pointer' }}>
                    Doctor {getSortIcon('doctor')}
                  </th>
                  <th onClick={() => handleSort('department')} style={{ cursor: 'pointer' }}>
                    Department {getSortIcon('department')}
                  </th>
                  <th onClick={() => handleSort('appointmentDate')} style={{ cursor: 'pointer' }}>
                    Date {getSortIcon('appointmentDate')}
                  </th>
                  <th onClick={() => handleSort('appointmentTime')} style={{ cursor: 'pointer' }}>
                    Time {getSortIcon('appointmentTime')}
                  </th>
                  <th onClick={() => handleSort('appointmentType')} style={{ cursor: 'pointer' }}>
                    Type {getSortIcon('appointmentType')}
                  </th>
                  <th onClick={() => handleSort('status')} style={{ cursor: 'pointer' }}>
                    Status {getSortIcon('status')}
                  </th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {appointments.map(a => (
                  <tr key={a.id}>
                    <td><span className="token-badge appointment-token">{a.tokenNumber}</span></td>
                    <td>
                      <div style={{ fontWeight: 600 }}>{a.patient?.fullName}</div>
                      <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>{a.patient?.phone}</div>
                    </td>
                    <td>
                      <div style={{ fontWeight: 600 }}>{a.doctor?.fullName}</div>
                      <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>{a.doctor?.specialization}</div>
                    </td>
                    <td>{a.department?.name}</td>
                    <td>{a.appointmentDate}</td>
                    <td>{a.appointmentTime}</td>
                    <td><Badge status={a.appointmentType} /></td>
                    <td><Badge status={a.status} /></td>
                    <td>
                      <div className="appointment-table-actions">
                        {a.status === 'pending' && (
                          <button className="btn btn-accent btn-sm" disabled={updating === a.id}
                            onClick={() => updateStatus(a.id, 'confirmed')}>Confirm</button>
                        )}
                        {a.status === 'confirmed' && (
                          <button className="btn btn-secondary btn-sm" disabled={updating === a.id}
                            onClick={() => updateStatus(a.id, 'completed')}>Complete</button>
                        )}
                        {(a.status === 'pending' || a.status === 'confirmed') && (
                          <ActionMenu
                            label="Actions"
                            items={[
                              ...(a.status === 'confirmed' ? [
                                { label: 'Collect payment & print', onSelect: () => openPaymentModal(a) },
                                { label: 'Print receipt', onSelect: () => openPaymentModal(a) },
                              ] : []),
                              { label: 'Cancel appointment', danger: true, disabled: updating === a.id, onSelect: () => setCancelTarget(a) },
                            ]}
                          />
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>

            {/* Mobile Cards */}
            <div className="appointments-mobile">
              {appointments.map(a => (
                <div className="appointment-card" key={a.id}>
                  <div className="appointment-card-header">
                    <span className="token-badge">{a.tokenNumber}</span>
                    <Badge status={a.status} />
                  </div>
                  <div className="appointment-card-body">
                    <div className="appointment-card-row">
                      <span className="appointment-card-label">Patient</span>
                      <span className="appointment-card-value">{a.patient?.fullName}</span>
                    </div>
                    <div className="appointment-card-row">
                      <span className="appointment-card-label">Phone</span>
                      <span className="appointment-card-value">{a.patient?.phone}</span>
                    </div>
                    <div className="appointment-card-row">
                      <span className="appointment-card-label">Doctor</span>
                      <span className="appointment-card-value">{a.doctor?.fullName}</span>
                    </div>
                    <div className="appointment-card-row">
                      <span className="appointment-card-label">Department</span>
                      <span className="appointment-card-value">{a.department?.name}</span>
                    </div>
                    <div className="appointment-card-row">
                      <span className="appointment-card-label">Date & Time</span>
                      <span className="appointment-card-value">{a.appointmentDate} at {a.appointmentTime}</span>
                    </div>
                    <div className="appointment-card-row">
                      <span className="appointment-card-label">Type</span>
                      <Badge status={a.appointmentType} />
                    </div>
                  </div>
                  <div className="appointment-card-actions">
                    {a.status === 'pending' && (
                      <button className="btn btn-accent btn-sm" disabled={updating === a.id}
                        onClick={() => updateStatus(a.id, 'confirmed')}>Confirm</button>
                    )}
                    {a.status === 'confirmed' && (
                      <button className="btn btn-secondary btn-sm" disabled={updating === a.id}
                        onClick={() => updateStatus(a.id, 'completed')}>Complete</button>
                    )}
                    {(a.status === 'pending' || a.status === 'confirmed') && (
                      <button className="btn btn-danger btn-sm" disabled={updating === a.id}
                        onClick={() => setCancelTarget(a)}>Cancel</button>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </>
        )}
      </div>

      {/* Pagination Controls */}
      {showLegacyPagination && totalPages > 1 && (
        <div style={{ marginTop: 20, display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 10, flexWrap: 'wrap' }}>
          <button 
            className="btn btn-secondary btn-sm"
            onClick={() => handlePageChange(0)}
            disabled={page === 0}
            title="First page"
          >
            ⏮
          </button>
          <button 
            className="btn btn-secondary btn-sm"
            onClick={() => handlePageChange(page - 1)}
            disabled={page === 0}
            title="Previous page"
          >
            ◀ Prev
          </button>
          
          <span style={{ padding: '0 15px', fontSize: 14 }}>
            Page {page + 1} of {totalPages}
            {totalElements > 0 && ` (${totalElements} records)`}
          </span>
          
          <button 
            className="btn btn-secondary btn-sm"
            onClick={() => handlePageChange(page + 1)}
            disabled={page >= totalPages - 1}
            title="Next page"
          >
            Next ▶
          </button>
          <button 
            className="btn btn-secondary btn-sm"
            onClick={() => handlePageChange(totalPages - 1)}
            disabled={page >= totalPages - 1}
            title="Last page"
          >
            ⏭
          </button>
        </div>
      )}
      <Pagination page={page} totalPages={totalPages} totalElements={totalElements} onChange={handlePageChange} disabled={loading} />

      <ConfirmDialog
        open={!!cancelTarget}
        title="Cancel appointment?"
        message={cancelTarget ? `This will cancel ${cancelTarget.patient?.fullName || 'this patient'}'s appointment.` : ''}
        confirmLabel="Cancel appointment"
        danger
        busy={updating === cancelTarget?.id}
        onClose={() => setCancelTarget(null)}
        onConfirm={async () => {
          if (!cancelTarget) return;
          await updateStatus(cancelTarget.id, 'cancelled');
          setCancelTarget(null);
        }}
      />
    </div>
  );
};

export default Appointments;

